global:
  scrape_interval: 5s
  external_labels:
    cluster: demo
    namespace: demo

scrape_configs:
  - job_name: demo/piko
    static_configs:
      - targets: ["piko-1:8002"]
        labels:
          pod: "piko-1"
      - targets: ["piko-2:8002"]
        labels:
          pod: "piko-2"
      - targets: ["piko-3:8002"]
        labels:
          pod: "piko-3"
