apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "piko.fullname" . }}
  labels:
    {{- include "piko.labels" . | nindent 4 }}
data:
  server.yaml: |
    cluster:
      node_id_prefix: ${POD_NAME}-
      join:
        - {{ include "piko.fullname" . }}
